set -g default-shell /usr/local/bin/zsh

# Titles
set-option -g set-titles on
set-option -g set-titles-string "#H:#S.#I.#P #W #T"

# Bells
set-option -g visual-bell off
set-option -g bell-action none

# Key shortcuts
set-option -g prefix C-a
unbind-key C-b
bind-key a send-prefix
bind-key C-a last-window

#Mmmm, vim-flavored
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind C-h resize-pane -L
bind C-j resize-pane -D
bind C-k resize-pane -U
bind C-l resize-pane -R

# easier to remember split commands
bind - split-window
bind | split-window -h

# Left status bar
set -g status-bg default
set -g status-left-fg colour235
set -g status-left-length 30
set -g status-left '#S'

# Window status bars
set -g window-status-current-format '#[fg=blue,noreverse,bold] #I : #W '
set -g window-status-format '#[fg=yellow] #I : #W '

# Right status bar
set -g status-right '#(rainbarf) #[fg=red]%Y-%m-%d #[fg=white]%I:%M'

# Message
set -g message-bg colour235
set -g message-fg white

# Panes
set -g pane-active-border-fg colour150

# Use vi mode
set-window-option -g mode-keys vi
set -g @shell_mode 'vi'

# fix copying
bind-key -Tcopy-mode-vi 'v' send -X begin-selection
bind-key -Tcopy-mode-vi 'y' send -X copy-selection


# other options
set -g base-index 1
bind q confirm kill-window
set -g default-terminal "screen-256color"

# Fix escape lag in emacs
set -s escape-time 0

# Fix Window titles
set -g allow-rename off

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'

# Some ressurect options
set -g @resurrect-processes 'vim nvim weechat htop nettop weechat ~termcal ~termclock'

run -b '~/.tmux/plugins/tpm/tpm'
