set -g default-shell /usr/local/bin/zsh

# Titles
set-option -g set-titles on
set-option -g set-titles-string "#H:#S.#I.#P #W #T"

# Bells
set-option -g visual-bell off
set-option -g bell-action none

# Key shortcuts
set-option -g prefix C-a
unbind-key C-b
bind-key a send-prefix
bind-key C-a last-window

#Mmmm, vim-flavored
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind C-h resize-pane -L 5
bind C-j resize-pane -D 5
bind C-k resize-pane -U 5
bind C-l resize-pane -R 5

# easier to remember split commands
bind - split-window
bind | split-window -h

# Left status bar
set -g status-bg default
set -g status-left-length 30
set -g status-left '#S'

# Window status bars
set -g window-status-current-format '#[fg=blue,noreverse,bold] #I : #W '
set -g window-status-format '#[fg=yellow] #I : #W '

# Right status bar
set -g status-right '#(rainbarf) #[fg=red]%Y-%m-%d #[fg=white]%I:%M'

# Use vi mode
set-window-option -g mode-keys vi
set -g @shell_mode 'vi'

# fix copying
bind-key -Tcopy-mode-vi 'v' send -X begin-selection
bind-key -Tcopy-mode-vi 'y' send -X copy-selection


# other options
set -g base-index 1
bind q confirm kill-window
set -g default-terminal "xterm-256color-italic"

# Fix escape lag in emacs
set -s escape-time 0

# Fix Window titles
set -g allow-rename off

# Fix random shit breaking in OS X Because apparently Steve Jobs is haunting me
# from the grave
set-option -g default-command "exec reattach-to-user-namespace -l $(which zsh)"
